sudo: required
dist: trusty
language: c
compiler: gcc
env:
  global:
    - CHROOT_DIR=/alpine
    - secure: q/ce56q/XlHRd8PZJp5SgzJipd7i37MbstBWkXIwuNI121fBF0LlBBpZHHnEVZikIvwkN0HPPydfXbL45pn/VnOaZCfdV0vj99Zv7Ln5ZIGCrygoPmynBLSzcRJl391+2+b/EKfYZaYhg+0GWXyE8SUfkzMxFU08kl/VE1Lw4KGIe86mbZDB6rWPj0ZTSlcZ74a1esnGs4eSrTpOwFEMb1l0Di25qYRpNFF3sHuzEQZ7KP0gsmipY3YE+azW6A6wVGT5azoUFvGkAfVrAC2jGK2rJTkI79rIxvcS4XkLWiaIXRjatB328JSwxFar2DiYHWeO7flgWoHwbqEEuGEShvq52Oc0hz0D+xIJ7QHgeLrnNdiGQpj1BnORHdZRim9u2H+eK7vetdkknUjPV2FQuKw/0v270JZOaEkNORdEuxCKOFH7A6TPbw+hxVITSD1DUE44wW14efo6IcQ3CBhj26jyuqpLIewkAfZE42M9+BEmqJGIALT6mKlU6cAwW3WjTLtgh6eTxWiCb+4u4xR0S808OH8WDAFGJOA9ggVKtDRbrqnozGTj2HzTo1m+eV8J1uFBjiOIitCIndayhcB2JUtjEDXRGDQ+yhK0E0GH5+emq1kQgPua/R++ubdOoj5117d87WnppJD1YLE+tBReATOOrMZ51W2Jy9zn1Vl8no8=  # GPG_PASS
  matrix:
    - ARCH=x86_64 LIBC=gnu
    - ARCH=x86_64 LIBC=musl
    - ARCH=armhf LIBC=musl
install:
  - sudo ./script/ci-install
script:
  - ./script/ci-build
deploy:
  - provider: releases
    api_key:
      secure: "pdRyPqnaNmN2xe74wYbNnB9OuVKgH+goMTQW1ald5BTAyTuS82OLBmuqhFucbPUTslgEl5HwDH0LWf0UqYyhmnOCY7dzw46VZHZR0jcdph9lXkIXM8/YaPjeM4z0myx/A/5LDj6s5XEYWkUAZru5zE3Aj8qViQYymPb4pb/rFBVjd4I52B8v9Ff74GJlPdMBKnoKgm7itjX1ppdsIb7zT24oNCkZoGRXb71KdgLEjarWoBxLJC3IH+XeZQMAWP6X43Nj0Mw1ECUtdT0NOyS2lr7NrK1NcyYpHVLsvpyYWFC6cEyp418TzDit3JYyi3EwhmzVSzzmGkYYNnAgbB6UXNrl4A3TQ6GEcZ0BFZpbfVjf2zTpuveLArcx93TfF873FGvuHm7eAkzxBQkxdh+Q/X9hj0kAfdC8dRH9KW8qNm8t3HuHyHbeiG3Nbn9SDcPRlyRyWiQtLsc0lIxDoRMQD9VcjPlFE5vqAwXJRATGp5OYJH/EyaIPkRyE53we0VrUJH2SFEXdT7CPLsbgVmeebR9ILacnaxZRYmWU8mDOmTtOj/rA9F3ji+508q9bX+v0EsslR0H2m4v5/lWUdUZnPkzzDJsd3AG3QwvQOjBr2LS6d2OZEQwrS2Fco/EDXy6KESjArQxdmy6+qzf9u0ekoLqNKPiuIVORv93UPsWJdZc="
    file: build/bc-bridge-*.tar.gz
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: script/ci-deploy
    skip_cleanup: true
    on:
      tags: true
      condition: "$LIBC = musl"
